name: srkr_study_app
description: A new Flutter project.
publish_to: 'none'
version: 2.0.0+7

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  firebase_storage: ^10.0.0
  url_launcher: ^6.1.5
  http: ^0.13.4
  fluttertoast: ^8.0.9
  rename: ^2.0.1
  google_mobile_ads: ^1.3.0
  new_version: ^0.3.1
  connectivity_plus: ^2.3.6
  carousel_slider: ^4.1.1
  firebase_core: ^1.20.1
  provider: ^5.0.0
  cloud_firestore: ^3.4.4
  firebase_auth: ^3.6.3
  email_validator: ^2.1.17
  intl: ^0.17.0
  photo_view: ^0.14.0
  flutterfire_ui: ^0.4.3+10
  firebase_database: ^9.1.7
  image_picker: ^0.8.6+4
  flutter_downloader: ^1.10.2
  path_provider: ^2.0.13
  cached_network_image: ^3.0.0
  flutter_staggered_grid_view: ^0.6.2
  image_gallery_saver: ^1.7.1





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/