name: srkr_study_app
description: A new Flutter project.
publish_to: 'none'
version: 3.0.10+18

environment:
  sdk: ">=2.12.0-dev.68.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_storage: ^11.2.5
  url_launcher: ^6.1.12
  http: ^0.13.0
  fluttertoast: ^8.2.2
  google_mobile_ads: ^3.0.0
  carousel_slider: ^4.2.1
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.5
  firebase_auth: ^4.7.2
  email_validator: ^2.1.17
  intl: ^0.18.1
  photo_view: ^0.14.0
  firebase_database: ^10.2.4
  image_picker: ^1.0.2
  path_provider: ^2.0.15
  flutter_local_notifications: ^15.1.0+1
  animations: ^2.0.7
  flutter_pdfview: ^1.3.1
  firebase_messaging: ^14.6.5
  webview_flutter: ^4.2.2
  marquee: ^2.2.3
  shared_preferences: ^2.2.0
  mailer: ^6.0.1








dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/