name: srkr_study_app
description: A new Flutter project.
publish_to: 'none'
version: 3.0.3+11

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.0
  firebase_storage: ^11.1.0
  url_launcher: ^6.1.10
  http: ^0.13.5
  fluttertoast: ^8.2.1
  rename: ^2.0.1
  google_mobile_ads: ^2.4.0
  new_version: ^0.3.1
  carousel_slider: ^4.2.1
  firebase_core: ^2.9.0
  cloud_firestore: ^4.5.0
  firebase_auth: ^4.4.0
  email_validator: ^2.1.17
  intl: ^0.17.0
  photo_view: ^0.14.0

  firebase_database: ^10.1.0
  image_picker: ^0.8.7+1
  path_provider: ^2.0.14
  cached_network_image: ^3.2.3
  syncfusion_flutter_pdfviewer: ^21.1.39
  flutter_local_notifications: ^13.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/