name: srkr_study_app
description: A new Flutter project.
publish_to: 'none'
version: 2023.11.14+26

environment:
  sdk: ">=2.12.0-dev.68.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  firebase_storage:
  url_launcher:
  http:
  fluttertoast:
#  google_mobile_ads:
#  youtube_explode_dart:
  carousel_slider:
  firebase_core:
  cloud_firestore:
  firebase_auth:
  email_validator:
  intl:
  photo_view:
  firebase_database:
  image_picker:
  path_provider:
  flutter_local_notifications:
#  animations:
  flutter_pdfview:
  firebase_messaging:
  marquee:
  shared_preferences:
  mailer:
#  open_file:
  flutter_tts:
#  visibility_detector:
  objectbox_flutter_libs:
#  flutter_speed_dial:
  youtube_player_flutter:
  youtube:
#  flutter_inappwebview:



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: test
      fonts:
        - asset: assets/fonts/SairaCondensed-Regular.ttf