name: srkr_study_app
description: A new Flutter project.
publish_to: 'none'
version: 2024.5.7+37

environment:
  sdk: '>=2.12.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:

  url_launcher:

  http:
  firebase_database:
  firebase_core:
  cloud_firestore:
  firebase_messaging:
  firebase_auth:

  email_validator:
  carousel_slider:
  intl:
  photo_view:

  path_provider:
  flutter_local_notifications:
  flutter_pdfview:
  shared_preferences:
  mailer:
  flutter_tts:
  fluttertoast:
  file_picker:
  dio:
  pdfx:
  open_filex:
  firebase_storage:
  google_fonts:

  google_mobile_ads:
  flutter_polls: ^0.1.6





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:


flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
#  assets:
#    - assets/
#  fonts:
#    - family: test
#      fonts:
#        - asset: assets/fonts/SairaCondensed-Regular.ttf