name: srkr_study_app
description: A new Flutter project.
publish_to: 'none'
version: 3.0.3+11

environment:
  sdk: ">=2.12.0-dev.68.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  shared_preferences: ^2.1.1
  firebase_storage: ^11.2.1
  url_launcher: ^6.1.11
  http: ^0.13.0
  fluttertoast: ^8.2.2
  rename: ^2.1.1
  google_mobile_ads: ^3.0.0

  carousel_slider: ^4.2.1
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  email_validator: ^2.1.17
  intl: ^0.18.1
  photo_view: ^0.14.0

  firebase_database: ^10.2.1
  image_picker: ^0.8.7+5
  path_provider: ^2.0.15
  cached_network_image: ^3.2.3
  flutter_local_notifications: ^14.1.0
  animations: ^2.0.7
  flutter_pdfview: ^1.3.1
  firebase_messaging: ^14.6.1
  webview_flutter: ^4.2.1







dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/