name: srkr_study_app
description: A new Flutter project.
publish_to: 'none'
version: 2023.12.31+28

environment:
  sdk: '>=3.2.0-272.0.dev <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  firebase_storage:
  url_launcher:
  http:


  carousel_slider:
  firebase_core:
  cloud_firestore:
  firebase_auth:
  email_validator:
  intl:
  photo_view:
  image_picker:
  path_provider:
  flutter_local_notifications:
  flutter_pdfview:
  firebase_messaging:
  shared_preferences:
  mailer:
  flutter_tts:
  fluttertoast: ^8.2.4
  objectbox_flutter_libs: ^1.3.0
  firebase_database: ^10.4.0




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: test
      fonts:
        - asset: assets/fonts/SairaCondensed-Regular.ttf