name: srkr_study_app
description: A new Flutter project.
publish_to: 'none'
version: 3.1.04+23

environment:
  sdk: ">=2.12.0-dev.68.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_storage: ^11.2.7
  url_launcher: ^6.1.12
  http: ^0.13.0
  fluttertoast: ^8.2.2
  #  google_mobile_ads: ^3.0.0
  carousel_slider: ^4.2.1
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.10.0
  email_validator: ^2.1.17
  intl: ^0.18.1
  photo_view: ^0.14.0
  firebase_database: ^10.2.6
  image_picker: ^1.0.2
  path_provider: ^2.0.15
  flutter_local_notifications: ^15.1.0+1
  animations: ^2.0.7
  flutter_pdfview: ^1.3.1
  firebase_messaging: ^14.6.8
  marquee: ^2.2.3
  shared_preferences: ^2.2.0
  mailer: ^6.0.1
  open_file: ^3.3.2
  flutter_tts: ^3.8.3
  visibility_detector: ^0.4.0+2
  objectbox_flutter_libs: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: test
      fonts:
        - asset: assets/fonts/SairaCondensed-Regular.ttf