// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ96orZOL0fZydFmCCAal1idQlxv7tuoM',
    appId: '1:1066742888174:web:f83a62f07cad01e36fe5ff',
    messagingSenderId: '1066742888174',
    projectId: 'esrkr-study-app',
    authDomain: 'esrkr-study-app.firebaseapp.com',
    databaseURL: 'https://esrkr-study-app-default-rtdb.firebaseio.com',
    storageBucket: 'esrkr-study-app.appspot.com',
    measurementId: 'G-K78QK25XRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDecRg9CXuUfrbC1l521xJgddVvKS10Vmg',
    appId: '1:1066742888174:android:e5301c70726884d56fe5ff',
    messagingSenderId: '1066742888174',
    projectId: 'esrkr-study-app',
    databaseURL: 'https://esrkr-study-app-default-rtdb.firebaseio.com',
    storageBucket: 'esrkr-study-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6zDKwWcyIXZSDrSVF3-jQ85EZkK-wSuI',
    appId: '1:1066742888174:ios:849dfaae8a550d1b6fe5ff',
    messagingSenderId: '1066742888174',
    projectId: 'esrkr-study-app',
    databaseURL: 'https://esrkr-study-app-default-rtdb.firebaseio.com',
    storageBucket: 'esrkr-study-app.appspot.com',
    androidClientId: '1066742888174-91n4k2bpv945407sf0j4miv02b3mualu.apps.googleusercontent.com',
    iosBundleId: 'com.nimmalasujith.esrkr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6zDKwWcyIXZSDrSVF3-jQ85EZkK-wSuI',
    appId: '1:1066742888174:ios:4e016339ca7b353c6fe5ff',
    messagingSenderId: '1066742888174',
    projectId: 'esrkr-study-app',
    databaseURL: 'https://esrkr-study-app-default-rtdb.firebaseio.com',
    storageBucket: 'esrkr-study-app.appspot.com',
    androidClientId: '1066742888174-91n4k2bpv945407sf0j4miv02b3mualu.apps.googleusercontent.com',
    iosBundleId: 'com.nimmalasujith.srkrStudyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ96orZOL0fZydFmCCAal1idQlxv7tuoM',
    appId: '1:1066742888174:web:efe81ba956b516c86fe5ff',
    messagingSenderId: '1066742888174',
    projectId: 'esrkr-study-app',
    authDomain: 'esrkr-study-app.firebaseapp.com',
    databaseURL: 'https://esrkr-study-app-default-rtdb.firebaseio.com',
    storageBucket: 'esrkr-study-app.appspot.com',
    measurementId: 'G-43X4BCHVYN',
  );

}